services:
  db:
    image: postgres:16-alpine
    container_name: app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: ./server/app
      dockerfile: Dockerfile
    container_name: app-api
    restart: unless-stopped
    env_file:
      - ./server/app/.env
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/app?schema=public
      PORT: 4000
      CORS_ORIGIN: http://localhost:3000
    command: sh -c "npx prisma migrate deploy && node dist/main.js"
volumes:
  pgdata:
